#程序运行端口
server:
  port: 8848

#数据库配置
spring:
  datasource:
    username: web_magic_data
    password: WANG2456
    url: jdbc:mysql://175.178.183.73:3306/web_magic_data?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 500000
  security:
    user:
      name: sympa
      password: 123456

