#程序运行端口
server:
  port: 8848

#数据库配置
spring:
  datasource:
    username: web_magic_data
    password: WANG2456
    url: jdbc:mysql://175.178.183.73:3306/web_magic_data?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 120000
    dbcp2:
      test-on-borrow: true
      validation-query: SELECT 1
  security:
    user:
      name: sympa
      password: 123456
  redis:
    database: 0
    host: 175.178.183.73
    port: 6380
    password: WANG2456
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
    timeout: 10000
  cache:
    redis:
      use-key-prefix: true
      key-prefix: sms_
      cache-null-values: false
      time-to-live: 10s
  kafka:
    bootstrap-servers: http://175.178.183.73:9092
cos:
  secretId: AKIDypUt42kD9qGSXYNG0Vt50iDTWO3RdJp7		# 密钥id
  secretKey: 6xYuXx99wXv89u1uY0GUYRAlAVfhcMtB		# 密钥key
  bucketName: zscacm-1302342664		# 需要使用的存储桶名称
  region: ap-guangzhou			# 存储桶地域